[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Disabled as it can be non-deterministic, affecting the resulting contract address.
bytecode_hash = "none"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
